FROM node:14.14-alpine
ENV NODE_ENV=development
ENV PARCEL_WORKERS=1
WORKDIR /usr/src/app
COPY package.json .
RUN npm install -g parcel-bundler
RUN npm install
COPY . .
CMD ["npm", "start"]
EXPOSE 3000
