language: generic
sudo: required
services:
  - docker

before_install: 
  # - docker build -t johnyworld/ts-test -f ./frontend/Dockerfile.dev ./frontend

script:
  # - docker run -e CI=true johnyworld/ts-test npm run test

after_success:
  docker-compose up
  # - docker build -t johnyworld/ts-server .
  # - docker build -t johnyworld/ts-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push tumssum_server
  - docker push tumssum_nginx

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: tumssum-web
  env: Tumssumweb-env
  bucket_name: elasticbeanstalk-ap-northeast-2-683369338492
  bucket_path: tumssum-web
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key_id: $AWS_SECRET_ACCESS_KEY
