version: '3.4'
services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    environment:
      NODE_ENV: development
      PARCEL_WORKERS: 2
    ports:
      - 3000:3000

  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /usr/src/app/client
  #     - .:/usr/src/app
  #   ports:
  #     - 8000:8000
  #   environment:
  #     DJANGO_DB_HOST: mysql
  #     DJANGO_DB_NAME: tumssumdev
  #     DJANGO_DB_USERNAME: root
  #     DJANGO_DB_PASSWORD: 
  #     DJANGO_DB_PORT: 3306

  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_DATABASE: tumssumdev
