version: '3.4'
services:

  client-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    environment:
      NODE_ENV: development
      PARCEL_WORKERS: 1
    ports:
      - 3000:3000

  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/usr/src/app
    ports:
      - 8000:8000
