version: '3.4'
services:

  nginx:
    restart: always
    ports:
      - 80:80
    volumes_from:
      - server:ro
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on : 
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      DJANGO_DB_HOST: $DJANGO_DB_HOST
      DJANGO_DB_NAME: $DJANGO_DB_NAME
      DJANGO_DB_USERNAME: $DJANGO_DB_USERNAME
      DJANGO_DB_PASSWORD: $DJANGO_DB_PASSWORD
      DJANGO_DB_PORT: $DJANGO_DB_PORT
    # ports:
    #   - 8000:8000
