version: '3.4'
services:

  nginx:
    restart: always
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on : 
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
