version: '3.4'
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      DJANGO_DB_HOST: $DJANGO_DB_HOST
      DJANGO_DB_NAME: $DJANGO_DB_NAME
      DJANGO_DB_USERNAME: $DJANGO_DB_USERNAME
      DJANGO_DB_PASSWORD: $DJANGO_DB_PASSWORD
      DJANGO_DB_PORT: $DJANGO_DB_PORT
    ports:
      - 8000:8000

  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_NAME: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_DATABASE: tumssumdev
