version: '3.4'

services:
  tsclient:
    build:
      context: client
      dockerfile: ./Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/usr/src/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
