version: '3.4'
services:

  tsclient:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    environment:
      NODE_ENV: production

