version: '3.4'

services:
  tumssumfrontend:
    image: tumssumfrontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    build:
      context: client
      dockerfile: ./Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app/client
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000

      