version: '3.4'
services:

  nginx:
    restart: always
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on : 
      - server
    expose:
      - 80

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
    environment:
      PARCEL_WORKERS: 1
      EMAIL_HOST_USER: $EMAIL_HOST_USER
      EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
      DJANGO_DB_HOST: $DJANGO_DB_HOST
      DJANGO_DB_NAME: $DJANGO_DB_NAME
      DJANGO_DB_USERNAME: $DJANGO_DB_USERNAME
      DJANGO_DB_PASSWORD: $DJANGO_DB_PASSWORD
      DJANGO_DB_PORT: $DJANGO_DB_PORT
    ports:
      - 8000:8000
    expose:
      - 5000
