# Generated by Django 3.2.3 on 2021-07-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_account_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='datetime',
            field=models.CharField(max_length=40),
        ),
    ]
