# Generated by Django 3.2.7 on 2022-02-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_budget_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='balance',
        ),
    ]
