# Generated by Django 3.2.3 on 2021-05-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(verbose_name='user created')),
            ],
        ),
    ]
