# Generated by Django 3.2.3 on 2021-05-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210523_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.CharField(blank=True, default='', max_length=7),
            preserve_default=False,
        ),
    ]
