# Generated by Django 3.2.3 on 2021-05-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
