# Generated by Django 3.2.3 on 2021-08-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_month_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
