# Generated by Django 3.2.3 on 2021-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210828_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='memo',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='category',
            name='memo',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
