# Generated by Django 3.2.3 on 2021-12-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211106_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
