# Generated by Django 3.2.3 on 2021-12-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_account_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
